parameters:
- name: subscriptionId
- name: keyVaultName
- name: secretName

steps:
- task: AzurePowerShell@5
  displayName:
  inputs:
    azurePowerShellVersion: 'LatestVersion'
    azureSubscription: ${{ parameters.subscriptionId }}
    pwsh: true
    scriptType: 'InlineScript'
    inline: |
      $secretValue = Get-AzKeyVaultSecret -VaultName ${{ parameters.keyVaultName }} -Name {{ parameters.secretName }} -AsPlainText
      Write-Host "##vso[task.setvariable variable=KVSecret;issecret=true;isreadonly=true]$secretValue"
