parameters:
- name: serviceConnectionName
- name: keyVaultName
- name: secretName

steps:
- task: AzurePowerShell@5
  displayName: Get Secret from Azure KeyVault
  inputs:
    azurePowerShellVersion: 'LatestVersion'
    azureSubscription: ${{ parameters.serviceConnectionName }}
    pwsh: true
    scriptType: 'InlineScript'
    inline: |
      $secretValue = Get-AzKeyVaultSecret -VaultName ${{ parameters.keyVaultName }} -Name {{ parameters.secretName }} -AsPlainText
      Write-Host "The returned secret value is $secretValue"
      Write-Host "##vso[task.setvariable variable=KVSecret;issecret=true]$secretValue"
